name: Publish site

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-site
      - name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build/
          path: /root/website/build
