name: Publish site

on: [push]

jobs:
  build:
    name: Build the site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-site
      - name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: site-root
          path: build
  push-to-staging:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download .zip
        uses: actions/download-artifact@v1
        with:
          name: site-root
      - name: Push to staging bucket
        env:
          AWS_ACCESS_KEY_ID: {{ secrets.website_publisher_access_key }}
          AWS_SECRET_ACCESS_KEY: {{ secrets.website_publisher_secret_key }}
          shell: bash
          run: aws s3 sync site-root s3://staging.andrewstahlman.com
